name: Deploy to Mac mini kedua

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync to target folder
        run: |
          rsync -av --delete $GITHUB_WORKSPACE/ /home/dedy/data/database/
